memodir = "/Users/sei/git/memo/_posts"
editor = "nvim"
column = 20
width = 0
selectcmd = "peco"
grepcmd = "grep -nH ${PATTERN} ${FILES}"
memotemplate = ""
assetsdir = "."
pluginsdir = "/Users/sei/.config/memo/plugins"
templatedirfile = ""
templatebodyfile = ""
